### ISSUE TITLE
OpenSSL - Issues

### ISSUE THREAD

**Issue by githubclientelety** [aws-samples/lambda-serverless-inference-fastapi#6]
Team, 

we are facing below issue while setting up this code base.  Any help on how to resolve this issue ?

ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'OpenSSL 1.0.2k-fips  26 Jan 2017'. See: https://github.com/urllib3/urllib3/issues/2168[INFO]	2023-06-26T04:43:12.161Z	75f5ea99-1186-4725-b573-9144cc4d3303	Waiting for application shutdown.

**Comment by DeCa09** [comment]
Hi, 
thanks for raising this issue.
The last PR should have fixed it. Can you pull the updated code and confirm that it works now?
