### ISSUE TITLE
Internal Server Error when testing endpoint

### ISSUE THREAD

**Issue by yeonmo317** [aws-samples/lambda-serverless-inference-fastapi#7]
Strictly followed the guide here.
https://aws.amazon.com/blogs/machine-learning/deploy-a-serverless-ml-inference-endpoint-of-large-language-models-using-fastapi-aws-lambda-and-aws-cdk/

What I see:
1. The root page successfully returns "Hello World"
2. The /question page successfully return UI page
3. But received "Internal Server Error" (Error: response status is 500) when testing with question used in the guide (question: "What is the color of my car now?" and context: "My car used to be blue but I painted red."
4. The response header has this line:  x-cache: Error from cloudfront 

When testing using Firefox browser:
![image](https://github.com/aws-samples/lambda-serverless-inference-fastapi/assets/129945927/c9a0903a-5091-4de7-af90-5778dcb2c2d0)

Given the error message mentions Firefox, also tested using Google:
![image](https://github.com/aws-samples/lambda-serverless-inference-fastapi/assets/129945927/2a9a5a59-77b7-40f1-90aa-8a046e550f9c)

Any help is greatly appreciated!

**Comment by DeCa09** [comment]
Hi,

thanks for raising this issue. 
This is linked to the same problem mentioned in #6 and should be fixed with the last PR. 

For further communication, please refer to the linked issue :)
